packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@clerk/nextjs": ^6.36.5
  "@clerk/types": ^4.101.9
  "@hookform/resolvers": ^5.1.1
  "@phosphor-icons/react": 2.1.10
  "@tanstack/react-query": ^5.83.0
  "@tanstack/react-table": ^8.21.3
  "@trpc/client": ^11.4.3
  "@trpc/tanstack-react-query": ^11.4.3
  eslint: ^9.28.0
  prettier: ^3.5.3
  react-hook-form: ^7.60.0
  sonner: ^2.0.6
  superjson: ^2.2.2
  tailwindcss: ^4.1.14
  typescript: ~5.9.2
  zod: ^3.25.49

catalogs:
  react19:
    "@types/node": ^24.10.1
    "@types/react": ~19.1.10
    "@types/react-dom": ~19.1.10
    react: 19.1.0
    react-dom: 19.1.0
