export const SEED_SUBJECTS = [
	{
		name: "Applied Science",
		code: "15CSE09T",
		alias: "applied-science",
		color: "#F97316",
	},
	{
		name: "Mathematics",
		code: "14MAT01T",
		alias: "mathematics",
		color: "#3B82F6",
	},
	{
		name: "Engineering Physics",
		code: "14PHY01T",
		alias: "engineering-physics",
		color: "#22C55E",
	},
	{
		name: "Engineering Chemistry",
		code: "14CHE01T",
		alias: "engineering-chemistry",
		color: "#A855F7",
	},
	{
		name: "English Communication",
		code: "14ENG01T",
		alias: "english-communication",
		color: "#EC4899",
	},
	{
		name: "Data Structures",
		code: "15CSE01T",
		alias: "data-structures",
		color: "#14B8A6",
	},
	{
		name: "Computer Organization",
		code: "15CSE02T",
		alias: "computer-organization",
		color: "#EAB308",
	},
	{
		name: "Digital Electronics",
		code: "15CSE03T",
		alias: "digital-electronics",
		color: "#6366F1",
	},
	{
		name: "Object Oriented Programming",
		code: "15CSE04T",
		alias: "object-oriented-programming",
		color: "#F97316",
	},
	{
		name: "Database Management Systems",
		code: "15CSE05T",
		alias: "database-management-systems",
		color: "#3B82F6",
	},
	{
		name: "Operating Systems",
		code: "15CSE06T",
		alias: "operating-systems",
		color: "#22C55E",
	},
	{
		name: "Computer Networks",
		code: "15CSE07T",
		alias: "computer-networks",
		color: "#A855F7",
	},
	{
		name: "Software Engineering",
		code: "15CSE08T",
		alias: "software-engineering",
		color: "#EC4899",
	},
	{
		name: "Theory of Computation",
		code: "15CSE10T",
		alias: "theory-of-computation",
		color: "#14B8A6",
	},
	{
		name: "Design and Analysis of Algorithms",
		code: "15CSE11T",
		alias: "design-analysis-algorithms",
		color: "#EAB308",
	},
	{
		name: "Web Technologies",
		code: "15CSE12T",
		alias: "web-technologies",
		color: "#6366F1",
	},
	{
		name: "Mobile Application Development",
		code: "15CSE13T",
		alias: "mobile-application-development",
		color: "#F97316",
	},
	{
		name: "Cloud Computing",
		code: "15CSE14T",
		alias: "cloud-computing",
		color: "#3B82F6",
	},
	{
		name: "Machine Learning",
		code: "15CSE15T",
		alias: "machine-learning",
		color: "#22C55E",
	},
	{
		name: "Artificial Intelligence",
		code: "15CSE16T",
		alias: "artificial-intelligence",
		color: "#A855F7",
	},
	{
		name: "Data Structures Lab",
		code: "15CSE01P",
		alias: "data-structures-lab",
		color: "#EC4899",
	},
	{ name: "OOP Lab", code: "15CSE02P", alias: "oop-lab", color: "#14B8A6" },
	{ name: "DBMS Lab", code: "15CSE03P", alias: "dbms-lab", color: "#EAB308" },
	{
		name: "Networks Lab",
		code: "15CSE04P",
		alias: "networks-lab",
		color: "#6366F1",
	},
	{
		name: "Web Technologies Lab",
		code: "15CSE05P",
		alias: "web-technologies-lab",
		color: "#F97316",
	},
	{
		name: "Engineering Mechanics",
		code: "14ME01T",
		alias: "engineering-mechanics",
		color: "#3B82F6",
	},
	{
		name: "Thermodynamics",
		code: "14ME02T",
		alias: "thermodynamics",
		color: "#22C55E",
	},
	{
		name: "Fluid Mechanics",
		code: "14ME03T",
		alias: "fluid-mechanics",
		color: "#A855F7",
	},
	{
		name: "Strength of Materials",
		code: "14ME04T",
		alias: "strength-of-materials",
		color: "#EC4899",
	},
	{
		name: "Manufacturing Processes",
		code: "14ME05T",
		alias: "manufacturing-processes",
		color: "#14B8A6",
	},
	{
		name: "Machine Design",
		code: "14ME06T",
		alias: "machine-design",
		color: "#EAB308",
	},
	{
		name: "Heat Transfer",
		code: "14ME07T",
		alias: "heat-transfer",
		color: "#6366F1",
	},
	{
		name: "Mechanics Lab",
		code: "14ME01P",
		alias: "mechanics-lab",
		color: "#F97316",
	},
	{ name: "Surveying", code: "14CE01T", alias: "surveying", color: "#3B82F6" },
	{
		name: "Structural Analysis",
		code: "14CE02T",
		alias: "structural-analysis",
		color: "#22C55E",
	},
	{
		name: "Concrete Technology",
		code: "14CE03T",
		alias: "concrete-technology",
		color: "#A855F7",
	},
	{
		name: "Geotechnical Engineering",
		code: "14CE04T",
		alias: "geotechnical-engineering",
		color: "#EC4899",
	},
	{
		name: "Transportation Engineering",
		code: "14CE05T",
		alias: "transportation-engineering",
		color: "#14B8A6",
	},
	{
		name: "Environmental Engineering",
		code: "14CE06T",
		alias: "environmental-engineering",
		color: "#EAB308",
	},
	{
		name: "Surveying Lab",
		code: "14CE01P",
		alias: "surveying-lab",
		color: "#6366F1",
	},
	{
		name: "Circuit Analysis",
		code: "14EE01T",
		alias: "circuit-analysis",
		color: "#F97316",
	},
	{
		name: "Electrical Machines",
		code: "14EE02T",
		alias: "electrical-machines",
		color: "#3B82F6",
	},
	{
		name: "Power Systems",
		code: "14EE03T",
		alias: "power-systems",
		color: "#22C55E",
	},
	{
		name: "Control Systems",
		code: "14EE04T",
		alias: "control-systems",
		color: "#A855F7",
	},
	{
		name: "Signals and Systems",
		code: "14EE05T",
		alias: "signals-and-systems",
		color: "#EC4899",
	},
	{
		name: "Electrical Machines Lab",
		code: "14EE01P",
		alias: "electrical-machines-lab",
		color: "#14B8A6",
	},
	{
		name: "Analog Electronics",
		code: "14EC01T",
		alias: "analog-electronics",
		color: "#EAB308",
	},
	{
		name: "Digital Signal Processing",
		code: "14EC02T",
		alias: "digital-signal-processing",
		color: "#6366F1",
	},
	{
		name: "Microprocessors",
		code: "14EC03T",
		alias: "microprocessors",
		color: "#F97316",
	},
	{
		name: "Communication Systems",
		code: "14EC04T",
		alias: "communication-systems",
		color: "#3B82F6",
	},
	{
		name: "VLSI Design",
		code: "14EC05T",
		alias: "vlsi-design",
		color: "#22C55E",
	},
	{
		name: "Electronics Lab",
		code: "14EC01P",
		alias: "electronics-lab",
		color: "#A855F7",
	},
	{
		name: "Industrial Management",
		code: "14HS01T",
		alias: "industrial-management",
		color: "#EC4899",
	},
	{
		name: "Entrepreneurship Development",
		code: "14HS02T",
		alias: "entrepreneurship-development",
		color: "#14B8A6",
	},
	{
		name: "Constitution of India",
		code: "14HS03T",
		alias: "constitution-of-india",
		color: "#EAB308",
	},
	{
		name: "Environmental Studies",
		code: "14HS04T",
		alias: "environmental-studies",
		color: "#6366F1",
	},
	{
		name: "Technical Seminar",
		code: "15HS01T",
		alias: "technical-seminar",
		color: "#F97316",
	},
] as const;
