export { branchRouter as branch } from './branch'
export { organizationRouter as organization } from './organization'
export { studentRouter as student } from './student'
export { subjectRouter as subject } from './subject'
export { timetableRouter as timetable } from './timetable'
